name: Audit

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-audit
      - run: cargo audit
